// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Symbol = 3,
  String = 4,
  Number = 5,
  List = 8,
  DefLike = 9,
  VarName = 10,
  Lambda = 11,
  Property = 12,
  Let = 13,
  Binding = 14,
  Operator = 15,
  Quote = 16
