// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlighting} from "./highlight.js"
const spec_trivialSymbol = {__proto__:null,label:59, lambda:63, let:67}
export const parser = LRParser.deserialize({
  version: 14,
  states: "'[QYQPOOOOQO'#C_'#C_OOQO'#Ct'#CtOnQPO'#CdOYQPO'#ClOOQO'#Cs'#CsOOQO'#Cm'#CmQYQPOOOOQO'#Ck'#CkOOQO'#Ce'#CeO!OQPO'#CxOOQO'#Cg'#CgO!WQPO'#CzOOQO'#Ci'#CiO!]QPO'#C|O!bQPO'#DOO!bQPO'#DOOOQO'#Cw'#CwO!iQPO,59OOOQO,59W,59WOOQO-E6k-E6kOOQO'#Cf'#CfO!nQPO,59dO!uQPO,59fO#QQPO,59hO#YQPO,59jOOQO1G.j1G.jO#aQPO1G/OOOQO'#Ch'#ChOOQO'#Cn'#CnO#hQPO1G/QO#sQPO1G/QO!OQPO'#CjOOQO'#Co'#CoO#zQPO1G/SO$SQPO1G/SOOQO-E6l-E6lO$ZQPO7+$lO$ZQPO7+$lO$bQPO,59UOOQO-E6m-E6mO$iQPO7+$nO$iQPO7+$nO$pQPO<<HWOOQO1G.p1G.pO$wQPO1G.pO$|QPO<<HYOOQO7+$[7+$[",
  stateData: "%W~OfOSPOS~OSQOTQOVROiPOjPOsSO~OmXOoZOq]OUrP~PYOiPOjPO~OVgO~OVhO~OUrX~PYOUjO~OUla~PYOUoOiPOjPO~OUsOVpO~OUra~PYOUli~PYOUuOiPOjPO~OUni~PYOUyOVpO~OUpi~PYOUnq~PYOU|O~PYOUpq~PYOUny~PYOU!PO~OUpy~PYOTi~",
  goto: "%RsPPPtPPPP!f!z!}#Q#T#X#[#`!f#c$V$]PPP$c!fPP${%OP%OP%OP%OrQOSV_`fikosuvwyz{!OQWRQeYSlgnRwpuTORSV_`fikosuvwyz{!ORYRRfYR[RTmgnR^RTqhrR`RQVOQ_R`dV_ikvz{!OQi`QkfQvoQzsQ{uR!OyQngRtnQrhRxrpUORV_`fikosuvyz{!OQcSR}wRbRRaR",
  nodeNames: "⚠ LineComment Program Symbol String Number ) ( List DefLike VarName Lambda Property Let Binding Operator Quote",
  maxTerm: 35,
  nodeProps: [
    ["openedBy", 6,"("],
    ["closedBy", 7,")"]
  ],
  propSources: [highlighting],
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "6Y~RlOX!yXY&]YZ&]Z]!y]^&]^p!ypq&]qr!yrs&nsw!ywx([xy(ayz(fz{!y{|(k|}!y}!O(k!O!P)o!P!Q!y!Q![0U!]!^4T!^#O!y#O#P#t#P#p!y#p#q4l#q;'S!y;'S;=`&V<%lO!y~#O[i~OX!yZ]!y^p!yqr!ysw!yz![!y!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~#ydi~OX!yXZ!yZ]!y]^!y^p!ypq!yqr!yrs!ysw!ywz!yz![!y![!^!y!^#O!y#O#P#t#P#p!y#p#q!y#q;'S!y;'S;=`%X;=`<%l!y<%lO!y~%^]i~OX!yZ]!y^p!yqr!ysw!yz![!y!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V;=`<%l!y<%lO!y~&YP;=`<%l!y~&bSf~XY&]YZ&]]^&]pq&]~&qVOr&nrs'Ws#O&n#O#P']#P;'S&n;'S;=`(U<%lO&n~']OS~~'`RO;'S&n;'S;=`'i;=`O&n~'lWOr&nrs'Ws#O&n#O#P']#P;'S&n;'S;=`(U;=`<%l&n<%lO&n~(XP;=`<%l&n~(aOs~~(fOV~~(kOU~~(p_i~OX!yZ]!y^p!yqr!ysw!yz!O!y!O!P)o!P!Q!y!Q![0U!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~)t]i~OX!yZ]!y^p!yqr!ysw!yz!Q!y!Q![*m!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~*taT~i~OX!yZ]!y^p!yqr!ysw!yz!Q!y!Q![*m!^!g!y!g!h+y!h#O!y#O#P#t#P#X!y#X#Y+y#Y#p!y#q;'S!y;'S;=`&V<%lO!y~,Oai~OX!yZ]!y^p!yqr!ysw!yz{!y{|-T|}!y}!O-T!O!Q!y!Q![.R!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~-Y]i~OX!yZ]!y^p!yqr!ysw!yz!Q!y!Q![.R!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~.Y_T~i~OX!yZ]!y^p!yqr!ysw!yz!Q!y!Q![.R!^!o!y!o!p/X!p#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~/`[T~i~OX!yZ]!y^p!yqr!ysw!yz![!y!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~0]cT~i~OX!yZ]!y^p!yqr!ysw!yz!O!y!O!P1h!P!Q!y!Q![0U!^!g!y!g!h+y!h#O!y#O#P#t#P#X!y#X#Y+y#Y#p!y#q;'S!y;'S;=`&V<%lO!y~1ocT~i~OX!yZ]!y^p!yqr!ysw!yz!Q!y!Q![1h!^!g!y!g!h+y!h!o!y!o!p2z!p#O!y#O#P#t#P#X!y#X#Y+y#Y#p!y#q;'S!y;'S;=`&V<%lO!y~3R`T~i~OX!yZ]!y^p!yqr!ysw!yz![!y!^!g!y!g!h+y!h#O!y#O#P#t#P#X!y#X#Y+y#Y#p!y#q;'S!y;'S;=`&V<%lO!y~4YSP~OY4TZ;'S4T;'S;=`4f<%lO4T~4iP;=`<%l4T~4oVO#O4l#O#P5U#P#p4l#p#q5}#q;'S4l;'S;=`6S<%lO4l~5XRO;'S4l;'S;=`5b;=`O4l~5eWO#O4l#O#P5U#P#p4l#p#q5}#q;'S4l;'S;=`6S;=`<%l4l<%lO4l~6SOj~~6VP;=`<%l4l",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  dynamicPrecedences: {"9":1,"11":2,"13":3},
  specialized: [{term: 25, get: (value) => spec_trivialSymbol[value] || -1}],
  tokenPrec: 189
})
