// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlighting} from "./highlight.js"
const spec_trivialSymbol = {__proto__:null,label:53, lambda:57}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%^QYQPOOOOQO'#C_'#C_OOQO'#Cq'#CqOnQPO'#CdOYQPO'#CjOOQO'#Cp'#CpOOQO'#Ck'#CkQYQPOOOOQO'#Ci'#CiOOQO'#Ce'#CeO{QPO'#CuOOQO'#Cg'#CgO!TQPO'#CwO!YQPO'#CyO!YQPO'#CyOOQO'#Ct'#CtO!aQPO,59OOOQO,59U,59UOOQO-E6i-E6iOOQO'#Cf'#CfO!fQPO,59aO!mQPO,59cO!xQPO,59eOOQO1G.j1G.jO#PQPO1G.{OOQO'#Ch'#ChOOQO'#Cl'#ClO#WQPO1G.}O#cQPO1G.}OOQO-E6j-E6jO#jQPO7+$iO#jQPO7+$iO#qQPO<<HT",
  stateData: "#{~OcOSPOS~OSQOTQOVROfPOgPOnSO~OjXOlZOUmP~PYOfPOgPO~OVeO~OUmX~PYOUgO~OUia~PYOUlOfPOgPO~OUma~PYOUii~PYOUnOfPOgPO~OUki~PYOUkq~PYOUky~PYOTf~",
  goto: "$RnPPPoPPPP!X!h!k!n!q!u!X!x#dPPP#j!XPP#{$OP$OP$OhQOSV]^dfhlnopQWRQcYTiekkTORSV]^dfhlnopRYRRdYR[RTjekR^RQVOQ]R[bV]fhopQf^QhdQolRpnQkeRmkhUORV]^dfhlnopRaSR`RR_R",
  nodeNames: "⚠ LineComment Program Symbol String Number ) ( List DefLike VarName Lambda Property Operator Quote",
  maxTerm: 30,
  nodeProps: [
    ["openedBy", 6,"("],
    ["closedBy", 7,")"]
  ],
  propSources: [highlighting],
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "6Y~RlOX!yXY&]YZ&]Z]!y]^&]^p!ypq&]qr!yrs&nsw!ywx([xy(ayz(fz{!y{|(k|}!y}!O(k!O!P)o!P!Q!y!Q![0U!]!^4T!^#O!y#O#P#t#P#p!y#p#q4l#q;'S!y;'S;=`&V<%lO!y~#O[f~OX!yZ]!y^p!yqr!ysw!yz![!y!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~#ydf~OX!yXZ!yZ]!y]^!y^p!ypq!yqr!yrs!ysw!ywz!yz![!y![!^!y!^#O!y#O#P#t#P#p!y#p#q!y#q;'S!y;'S;=`%X;=`<%l!y<%lO!y~%^]f~OX!yZ]!y^p!yqr!ysw!yz![!y!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V;=`<%l!y<%lO!y~&YP;=`<%l!y~&bSc~XY&]YZ&]]^&]pq&]~&qVOr&nrs'Ws#O&n#O#P']#P;'S&n;'S;=`(U<%lO&n~']OS~~'`RO;'S&n;'S;=`'i;=`O&n~'lWOr&nrs'Ws#O&n#O#P']#P;'S&n;'S;=`(U;=`<%l&n<%lO&n~(XP;=`<%l&n~(aOn~~(fOV~~(kOU~~(p_f~OX!yZ]!y^p!yqr!ysw!yz!O!y!O!P)o!P!Q!y!Q![0U!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~)t]f~OX!yZ]!y^p!yqr!ysw!yz!Q!y!Q![*m!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~*taT~f~OX!yZ]!y^p!yqr!ysw!yz!Q!y!Q![*m!^!g!y!g!h+y!h#O!y#O#P#t#P#X!y#X#Y+y#Y#p!y#q;'S!y;'S;=`&V<%lO!y~,Oaf~OX!yZ]!y^p!yqr!ysw!yz{!y{|-T|}!y}!O-T!O!Q!y!Q![.R!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~-Y]f~OX!yZ]!y^p!yqr!ysw!yz!Q!y!Q![.R!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~.Y_T~f~OX!yZ]!y^p!yqr!ysw!yz!Q!y!Q![.R!^!o!y!o!p/X!p#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~/`[T~f~OX!yZ]!y^p!yqr!ysw!yz![!y!^#O!y#O#P#t#P#p!y#q;'S!y;'S;=`&V<%lO!y~0]cT~f~OX!yZ]!y^p!yqr!ysw!yz!O!y!O!P1h!P!Q!y!Q![0U!^!g!y!g!h+y!h#O!y#O#P#t#P#X!y#X#Y+y#Y#p!y#q;'S!y;'S;=`&V<%lO!y~1ocT~f~OX!yZ]!y^p!yqr!ysw!yz!Q!y!Q![1h!^!g!y!g!h+y!h!o!y!o!p2z!p#O!y#O#P#t#P#X!y#X#Y+y#Y#p!y#q;'S!y;'S;=`&V<%lO!y~3R`T~f~OX!yZ]!y^p!yqr!ysw!yz![!y!^!g!y!g!h+y!h#O!y#O#P#t#P#X!y#X#Y+y#Y#p!y#q;'S!y;'S;=`&V<%lO!y~4YSP~OY4TZ;'S4T;'S;=`4f<%lO4T~4iP;=`<%l4T~4oVO#O4l#O#P5U#P#p4l#p#q5}#q;'S4l;'S;=`6S<%lO4l~5XRO;'S4l;'S;=`5b;=`O4l~5eWO#O4l#O#P5U#P#p4l#p#q5}#q;'S4l;'S;=`6S;=`<%l4l<%lO4l~6SOg~~6VP;=`<%l4l",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  dynamicPrecedences: {"9":1,"11":2},
  specialized: [{term: 22, get: (value) => spec_trivialSymbol[value] || -1}],
  tokenPrec: 132
})
